# Generated by Django 5.0 on 2023-12-13 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutoPart",
            fields=[
                ("auto_part_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "auto_part",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("client_id", models.AutoField(primary_key=True, serialize=False)),
                ("organization_name", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("phone_num", models.IntegerField()),
            ],
            options={
                "db_table": "client",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("time_of_work", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
            options={
                "db_table": "service",
            },
        ),
        migrations.CreateModel(
            name="TypeService",
            fields=[
                (
                    "type_service_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name_service", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "type_service",
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("contract_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateTimeField()),
                (
                    "current_account",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("duration", models.IntegerField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.client"
                    ),
                ),
            ],
            options={
                "db_table": "contract",
            },
        ),
        migrations.CreateModel(
            name="ContractService",
            fields=[
                (
                    "contract_service_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("price", models.IntegerField()),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.contract"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.service"
                    ),
                ),
            ],
            options={
                "db_table": "contract_service",
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="services",
            field=models.ManyToManyField(
                through="app.ContractService", to="app.service"
            ),
        ),
        migrations.CreateModel(
            name="ServiceAutoPart",
            fields=[
                (
                    "service_auto_part_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "auto_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.autopart"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.service"
                    ),
                ),
            ],
            options={
                "db_table": "service_auto_part",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="type_service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.typeservice"
            ),
        ),
    ]
