# Generated by Django 5.0 on 2023-12-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="parts",
            field=models.ManyToManyField(
                through="app.ServiceAutoPart", to="app.autopart"
            ),
        ),
    ]
